version: 2.1

orbs:
  node: circleci/node@7.1.0
  aws: circleci/aws-cli@5.2.0

jobs:
  build:
    docker:
        - image: circleci/node:14.17
    steps:
      -  checkout
      - node/install-packages:
          package-manager: npm
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      - run:
          name: Back-End Install
          command: |
            npm run backend:install
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
