version: 2.1

orbs:
  node: circleci/node@7.1.0
  aws-cli: circleci/aws-cli@5.2.0

jobs:
  build:
    working_directory: ~/storefront
    docker:
      - image: cimg/node:20.11.1
    steps:
      - checkout
      - run:
          name: Install Front-End
          command: |
            cd storefront_frontend
            rm -rf node_modules package-lock.json
            npm cache clean --force
            npm install
            npm install @angular-devkit/build-angular --save-dev
            sudo npm link @angular/cli
            cd ..
      - run:
          name: Install Back-End
          command: |
            cd backend_api
            rm -rf node_modules package-lock.json
            npm cache clean --force
            npm ci
            cd ..
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      - run:
          name: Back-End Build
          command: npm run backend:build

  deploy:
    docker:
      - image: "cimg/python:3.11-node"
    steps:
      - checkout
      - run:
          name: Set Up Environment Variables
          command: |
            eb setenv \
              POSTGRES_HOST="${POSTGRES_HOST}" \
              POSTGRES_PORT="${POSTGRES_PORT}" \
              POSTGRES_DB="${POSTGRES_DB}" \
              POSTGRES_USER="${POSTGRES_USER}" \
              POSTGRES_PASSWORD="${POSTGRES_PASSWORD}" \
              PORT="${PORT}" \
              ENV="${ENV}" \
              NODE_ENV="${NODE_ENV}" \
              JWT_SECRET="${JWT_SECRET}" \
              BCRYPT_PASSWORD="${BCRYPT_PASSWORD}" \
              SALT_ROUNDS="${SALT_ROUNDS}" \
              AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}" \
              AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}" \
              AWS_DEFAULT_REGION="${AWS_DEFAULT_REGION}" \
              AWS_BUCKET_NAME="${AWS_BUCKET_NAME}"
            echo "Elastic Beanstalk Environment variables have been set"
      - aws-cli/setup
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip install --user awsebcli
            echo 'export PATH=$PATH:$HOME/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify EB CLI Installation
          command: eb --version
      - run:
          name: Front-End Deploy
          command: npm run frontend:deploy
      - run:
          name: Back-End Deploy
          command: npm run backend:deploy

workflows:
  build-hold-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master