version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    docker:
      - image: "cimg/node:20.11.1"
    steps:
      - checkout
      - run:
          name: Setup Environment
          command: |
            sudo npm install -g npm@8.19.4
            sudo npm install -g @angular/cli@19.1.7
            npm --version
            ng version
      - run:
          name: Frontend Build
          command: |
            cd frontend
            rm -rf node_modules package-lock.json
            npm install --legacy-peer-deps
            export PATH="$PATH:./node_modules/.bin"
            ng version
            ng build
      - run:
          name: Backend Build
          command: npm run backend:build
      - run:
          name: Backend Lint
          command: npm run backend:lint
      - save_cache:
          paths: [frontend/node_modules, backend_api/node_modules]
          key: deps-{{ checksum "package.json" }}