version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    docker:
      - image: "cimg/node:20.11.1"
    steps:
      - checkout
      - run:
          name: Set Up Environment Variables
          command: |
            chmod +x ./setup_env.sh
            source ./setup_env.sh
      - run:
          name: Install Dependencies and Build
          command: |
            # Install Angular CLI globally
            sudo npm install -g @angular/cli@19.1.7
            
            # Go to frontend directory
            cd frontend
            
            # Clean install
            rm -rf node_modules package-lock.json
            
            # Install production dependencies first
            npm install
            
            # Install dev dependencies explicitly
            npm install --save-dev @angular-devkit/build-angular@19.1.7
            npm install --save-dev @angular/cli@19.1.7
            npm install --save-dev @angular/compiler-cli@19.1.6
            
            # Show installed packages for debugging
            echo "Showing installed packages:"
            npm list --depth=0
      - run:
          name: Install Angular Builder
          command: |
            cd frontend
            npm install --save-dev @angular-devkit/build-angular@19.1.7
      - run:
          name: Frontend Build
          command: |
            cd frontend
            echo "Cleaning npm cache..."
            npm cache clean --force
            echo "Removing existing node_modules..."
            rm -rf node_modules package-lock.json
            echo "Installing all dependencies..."
            npm install --legacy-peer-deps
            echo "Verifying Angular CLI installation..."
            npm list @angular/cli
            echo "Verifying build-angular installation..."
            npm list @angular-devkit/build-angular
            echo "Building project..."
            npm run build
      - run:
          name: Backend Build
          command: npm run backend:build
      - run:
          name: Backend Lint
          command: npm run backend:lint
      - save_cache:
          paths: [frontend/node_modules, backend_api/node_modules]
          key: deps-{{ checksum "package.json" }}

  deploy:
    docker:
      - image: "cimg/python:3.11-node"
    steps:
      - checkout
      - run:
          name: Set Up Environment Variables
          command: |
            chmod +x ./setup_env.sh
            source ./setup_env.sh
      - restore_cache:
          keys: ['deps-{{ checksum "package.json" }}']
      - aws-cli/setup:
          profile-name: default
      - run:
                name: Install Node.js
                command: |
                  curl -fsSL https://deb.nodesource.com/setup_20.x | sudo -E bash -
                  sudo apt-get install -y nodejs
                  # Set the specific Node version
                  sudo npm install -g n
                  sudo n 20.11.1
      - run:
          name: Install Elastic Beanstalk CLI
          command: |
            sudo apt-get update
            sudo apt-get install -y python3-pip
            pip install --user awsebcli
            echo 'export PATH=$PATH:$HOME/.local/bin' >> $BASH_ENV
            source $BASH_ENV
      - run:
          name: Verify EB CLI Installation
          command: eb --version
      - run:
          name: Frontend Deploy
          command: npm run frontend:deploy
      - run:
          name: Backend Deploy
          command: npm run backend:deploy

workflows:
  build-hold-deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
          filters:
            branches:
              only: master