version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    docker:
      - image: "cimg/node:20.11.1"
    working_directory: ~/storefront
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "frontend/package.json" }}
      - run:
          name: Frontend Build
          command: |
            cd frontend
            echo "Current directory: $(pwd)"
            
            # Remove existing installations
            rm -rf node_modules package-lock.json
            
            # Install global Angular CLI first
            echo "Installing global Angular CLI..."
            sudo npm install -g @angular/cli@19.1.7
            
            # Create .npmrc
            echo "legacy-peer-deps=true" > .npmrc
            echo "strict-peer-dependencies=false" >> .npmrc
            
            # Install dependencies
            echo "Installing dependencies..."
            npm install --save-exact @angular/cli@19.1.7
            npm install --save-exact @angular/core@19.1.6
            npm install --save-exact @angular/common@19.1.6
            npm install --save-exact @angular/compiler@19.1.6
            npm install --save-exact @angular/compiler-cli@19.1.6
            npm install --save-exact @angular-devkit/build-angular@19.1.7
            npm install --save-exact typescript@5.6.2
            
            # Install remaining packages
            npm install --legacy-peer-deps
            
            echo "Verifying installations..."
            which ng
            ng version
            
            echo "Starting build..."
            ng build --configuration=production
      - run:
          name: Backend Build
          command: npm run backend:build
      - run:
          name: Backend Lint
          command: npm run backend:lint
      - save_cache:
          paths: 
            - frontend/node_modules
            - backend_api/node_modules
          key: v1-deps-{{ checksum "frontend/package.json" }}