version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1

jobs:
  build:
    docker:
      - image: "cimg/node:20.11.1"
    working_directory: ~/storefront
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "frontend/package.json" }}
      - run:
          name: Frontend Build
          command: |
            cd frontend
            echo "Current directory: $(pwd)"
            
            # Clean installation
            rm -rf node_modules package-lock.json
            
            # Create .npmrc
            echo "legacy-peer-deps=true" > .npmrc
            echo "strict-peer-dependencies=false" >> .npmrc
            
            # First install the CLI and core packages
            npm install --save-exact @angular/cli@19.1.7 \
                                   @angular-devkit/build-angular@19.1.7 \
                                   @angular/core@19.1.6 \
                                   @angular/common@19.1.6 \
                                   @angular/compiler@19.1.6 \
                                   @angular/compiler-cli@19.1.6 \
                                   typescript@5.6.2
            
            # Install remaining dependencies
            npm install --legacy-peer-deps
            
            echo "Verifying installations..."
            npm list @angular-devkit/build-angular
            npm list @angular/compiler-cli
            npm list typescript
            
            echo "Starting build..."
            ./node_modules/.bin/ng version
            ./node_modules/.bin/ng build --configuration=production
      - run:
          name: Backend Build
          command: npm run backend:build
      - run:
          name: Backend Lint
          command: npm run backend:lint
      - save_cache:
          paths: 
            - frontend/node_modules
            - backend_api/node_modules
          key: v1-deps-{{ checksum "frontend/package.json" }}